version: '{build}'
image: Visual Studio 2017
skip_commits:
 files:
   - docs/*
   - '**/*.md'

# Only fetch the latest commits to reduce time to download on agent, but support pushes containing multiple commits
clone_depth: 50

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

environment:
  codecov_upload_token:
    secure: 713yzE0R2Ek0JZTp+7uR3Upclc+jiIlM3Gf0UQ1Nbb5K09oXhE42hP8KWQngZ9ko

# Uncomment me to enable Remote Desktop for the duration of the build (when debugging hanging builds).
# Password is configured as envvar APPVEYOR_RDP_PASSWORD in AppVeyor UI.
# init:
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Uncomment me to enable Remote Desktop AFTER build. Build is blocked until a special "lock" file on VM desktop is deleted (max 60 mins).
# Password is configured as envvar APPVEYOR_RDP_PASSWORD in AppVeyor UI.
# on_finish:
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
- ps: |
    # Build, test, pack and push nugets
    .\\build-with-wrc.bat
    $BuildExitCode = $LASTEXITCODE

    # Upload test results to AppVeyor
    $wc = New-Object 'System.Net.WebClient'

    if (Test-Path .\\Artifacts\\Logs\\) {
        Get-ChildItem .\\Artifacts\\Logs\\*Test*.xml | %{
            $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", $_.FullName)
        }
    }

    if ($BuildExitCode -ne 0) {
        Write-Host "Build failed with exit code $BuildExitCode."
        exit $BuildExitCode
    }

# Do not build feature branch with open Pull Requests to avoid building twice
skip_branch_with_pr: true

before_test:
- dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools

test_script:
- "Tools/OpenCover\OpenCover.Console.exe" -version
- "Tools/OpenCover\OpenCover.Console.exe" -target:"dotnet.exe" -targetargs:"test UnitsNet.Tests" -output:"Artifacts/Coverage/UnitsNet.Tests.coverage.xml" -filter:"+[UnitsNet*]* -[UnitsNet.Tests*]*" -oldstyle -register:user
- "Tools/OpenCover\OpenCover.Console.exe" -target:"dotnet.exe" -targetargs:"test UnitsNet.Serialization.JsonNet.CompatibilityTests" -output:"Artifacts/Coverage/UnitsNet.Serialization.JsonNet.CompatibilityTests.coverage.xml" -filter:"+[UnitsNet*]* -[UnitsNet.Tests*]*" -oldstyle -register:user
- "Tools/OpenCover\OpenCover.Console.exe" -target:"dotnet.exe" -targetargs:"test UnitsNet.Serialization.JsonNet.Tests" -output:"Artifacts/Coverage/UnitsNet.Serialization.JsonNet.Tests.coverage.xml" -filter:"+[UnitsNet*]* -[UnitsNet.Tests*]*" -oldstyle -register:user

after_test:
- "Tools/reportgenerator.exe" -reports:Artifacts/Coverage/UnitsNet.Tests.coverage.xml;Artifacts/Coverage/UnitsNet.Serialization.JsonNet.CompatibilityTests.coverage.xml;Artifacts/Coverage/UnitsNet.Serialization.JsonNet.Tests.coverage.xml -targetdir:Artifacts/Coverage -reporttypes:HtmlSummary
- ps: |
    $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
    Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
    bash codecov.sh -f "Artifacts/Coverage/*.coverage.xml" -t $env:codecov_upload_token

artifacts:
- path: Artifacts\UnitsNet.zip
- path: 'Artifacts\NuGet\*.nupkg' # find all NuGet packages recursively
- path: Artifacts\Coverage

deploy:
- provider: NuGet
  api_key:
    secure: NlJ+D6kXfgU6RgRuf9okylLDENp8DA3tTRSC6UHBNbRS9ZAvRrC3Z0++Mr5VtGvz
  on:
    branch: master

- provider: NuGet
  api_key:
    secure: NlJ+D6kXfgU6RgRuf9okylLDENp8DA3tTRSC6UHBNbRS9ZAvRrC3Z0++Mr5VtGvz
  on:
    branch: release/*
