version: '{build}'
image: Visual Studio 2017
only_commits:
  files:
    - appveyor.yml
    - '**/*.sln'
    - '**/*.csproj'
    - '**/*.props'
    - '**/*.nuspec'
    - '**/*.cs'
    - '**/*.json'
    - '**/*.ps1'
    - '**/*.psm1'
    - '**/*.bat'
build_script:
- ps: |
    #####################################
    # Build, test, pack and push nugets
    #####################################

    .\\build.bat
    $BuildExitCode = $LASTEXITCODE

    #####################################
    # Upload test results to AppVeyor
    #####################################

    $wc = New-Object 'System.Net.WebClient'

    if (Test-Path .\\Artifacts\\Logs\\) {
        Get-ChildItem .\\Artifacts\\Logs\\*Test*.xml | %{
            $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", $_.FullName)
        }
    }

    if ($BuildExitCode -ne 0) {
        Write-Host "Build failed with exit code $BuildExitCode."
        exit $BuildExitCode
    }
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
test: off
artifacts:
- path: Artifacts\UnitsNet.zip
- path: 'Artifacts\NuGet\*.nupkg' # find all NuGet packages recursively
environment:
  api_key:
    secure: Onn5DCtRxwNADYG8i4snNuUOE5qhUsUSv5unaY5SMLv4l2FbRnIUlbdVw02s39Xk
deploy:
- provider: NuGet
  api_key:
    secure: Onn5DCtRxwNADYG8i4snNuUOE5qhUsUSv5unaY5SMLv4l2FbRnIUlbdVw02s39Xk
  skip_symbols: false
  on:
    branch: master

